src/Entity/Tarifables.php
<?php

namespace App\Entity;

use App\Repository\TarifablesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TarifablesRepository::class)]
class Tarifables
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?bool $extra_asiento = null;

    #[ORM\Column]
    private ?bool $factura_maleta = null;

    #[ORM\Column]
    private ?bool $extra_seguro = null;

    #[ORM\Column]
    private ?bool $business = null;

    #[ORM\Column(length: 7)]
    private ?string $Precio = null;

    #[ORM\Column(length: 255)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $Descripcion = null;

    #[ORM\OneToMany(mappedBy: 'Tarifables', targetEntity: Facturacion::class)]
    private Collection $facturacions;

    public function __construct()
    {
        $this->facturacions = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getExtraAsiento(): ?bool
    {
        return $this->extra_asiento;
    }

    public function setExtraAsiento(bool $extra_asiento): self
    {
        $this->extra_asiento = $extra_asiento;

        return $this;
    }

    public function isFacturaMaleta(): ?bool
    {
        return $this->factura_maleta;
    }

    public function setFacturaMaleta(bool $factura_maleta): self
    {
        $this->factura_maleta = $factura_maleta;

        return $this;
    }

    public function getExtraSeguro(): ?bool
    {
        return $this->extra_seguro;
    }

    public function setExtraSeguro(bool $extra_seguro): self
    {
        $this->extra_seguro = $extra_seguro;

        return $this;
    }

    public function isBusiness(): ?bool
    {
        return $this->business;
    }

    public function setBusiness(bool $business): self
    {
        $this->business = $business;

        return $this;
    }

    public function getPrecio(): ?string
    {
        return $this->Precio;
    }

    public function setPrecio(string $Precio): self
    {
        $this->Precio = $Precio;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(string $Descripcion): self
    {
        $this->Descripcion = $Descripcion;

        return $this;
    }

    /**
     * @return Collection<int, Facturacion>
     */
    public function getFacturacions(): Collection
    {
        return $this->facturacions;
    }

    public function addFacturacion(Facturacion $facturacion): self
    {
        if (!$this->facturacions->contains($facturacion)) {
            $this->facturacions->add($facturacion);
            $facturacion->setTarifables($this);
        }

        return $this;
    }

    public function removeFacturacion(Facturacion $facturacion): self
    {
        if ($this->facturacions->removeElement($facturacion)) {
            // set the owning side to null (unless already changed)
            if ($facturacion->getTarifables() === $this) {
                $facturacion->setTarifables(null);
            }
        }

        return $this;
    }
}

templates/admaviones.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
{{ parent() }}


<script>
    function confirmacion()
    {

        var respuesta=confirm("¿Desea realmente borrar el registro?");
        if (respuesta==true)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
</script>
{% endblock %}
{% block title %}Register{% endblock %}

{% block body %}
{{ parent() }}
<header>

</header>

<section class="pt-150 cuerpo fondoseccion">
<div class=" w-50 offset-lg-3 offset-md-1 offset-sm-3">
<h2 class="text-center">LISTADO DE AVIONES</h2>
</div>
<table class="table table-dark table-hover w-50  offset-lg-3 offset-md-1 offset-sm-3">
<thead>
<tr>
<th class="d-none">ID</th><th>CODIGO</th><th>MODELO</th><th>ACCIONES</th>
</tr>
</thead>
<tbody>
{% for avion in aviones %}
<tr id="{{avion.id}}" class="filasjuego tr:hover">
<td class="d-none">{{avion.id}}</td><td>{{avion.codigo}}</td><td>{{avion.modelo}}</td><td><a href="/admin/editaavion/{{avion.id}}" class=""><i class="fas fa-edit "></i></a><a href="/admin/deleteavion/{{avion.id}}" onclick="return confirmacion()"><i class="fas fa-trash ml-5"></i></a></td>
</tr>
{% endfor %}
</tbody>
</table>

<div class="d-flex justify-content-between w-50  offset-lg-3 offset-md-1 offset-sm-3">

<a href="/admin/nuevoavion2" class="btn btn-primary">Añadir</a>

{% if totalpgs > 0 %}
     <ul class="pagination">
     {% if pagina != 1 %}
                  <li class="page-item"><a class="page-link" href="/admin/listaavion/{{pagina - 1}}">&laquo;</a></li>
    {% if pagina != 2 %}
                  <li class="page-item"><a class="page-link" href="/admin/listaavion/{{pagina - 2}}">{{pagina - 2}}</a></li>
    {% endif %}
                  <li class="page-item"><a class="page-link" href="/admin/listaavion/{{pagina - 1}}">{{pagina - 1}}</a></li>
     {% endif %}
                  
                  <li class="page-item active"><a class="page-link" href="/admin/listaavion/{{pagina}}">{{pagina}}</a></li>
                  
    {% if pagina != totalpgs %} 
                  <li class="page-item"><a class="page-link" href="/admin/listaavion/{{pagina + 1}}">{{pagina + 1}}</a></li>
    {% if pagina != (totalpgs - 1 )%}
                  <li class="page-item"><a class="page-link" href="/admin/listaavion/{{pagina + 2}}">{{pagina + 2}}</a></li>
    {% endif %}              
                  <li class="page-item"><a class="page-link" href="/admin/listaavion/{{pagina + 1}}">&raquo;</a></li>
    {% endif %}
    </ul>  
{% endif %}

{% if ( pagina * 5 ) >= totalreg %}
    <p>(De {{iniciolimit + 1}} a {{totalreg}}. Total, {{totalreg}} registros.)</p>
{% else %}
    <p>(De {{iniciolimit + 1}} a {{pagina * 5}}. Total, {{totalreg}} registros.)</p>
{% endif %}
</div>

</section>

{% block footer %}
       {# <footer class="footer">            
                <p>Copyright <script>document.write(new Date().getFullYear())</script> &copy; <a href="http://www.devcrud.com">Xokas and co</a></p>
            </footer>#}
            <div class="fondoseccion text-center footer-pd">
                AIRES
            </div>
{% endblock %}
{% endblock %}

templates/admreservas.html.twig
{{dump(vueloida,vuelovuelta,tarifa,avionida,asientoelegidoIda,asientoelegidoVuelta)}}

templates/admusuarios.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
{{ parent() }}


<script>
    function confirmacion()
    {

        var respuesta=confirm("¿Desea realmente borrar el registro?");
        if (respuesta==true)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
</script>
{% endblock %}
{% block title %}Register{% endblock %}

{% block body %}
{{ parent() }}
<header>

</header>

<section class="pt-150 cuerpo fondoseccion">
<div class=" w-50 offset-lg-3 offset-md-3 offset-sm-2">
<h2 class="text-center">LISTADO DE USUARIOS</h2>
</div>
<table class="table table-dark table-hover w-50 offset-lg-3 offset-md-3 offset-sm-2">
<thead>
<tr>
<th class="d-none">ID</th><th>NOMBRE</th><th>E-MAIL</th><th>DNI</th>
</tr>
</thead>
<tbody>
{% for usuario in usuarios %}
<tr id="{{usuario.id}}" class="filasjuego tr:hover">
<td class="d-none">{{usuario.id}}</td><td>{{usuario.apellido1 ~ ' ' ~ usuario.apellido2 ~ ', ' ~ usuario.nombre}}</td><td>{{usuario.email}}</td><td>{{usuario.dni}}</td>
</tr>
{% endfor %}
</tbody>
</table>

<div class="d-flex justify-content-between w-50 offset-lg-3 offset-md-3 offset-sm-2">

{% if totalpgs > 0 %}
     <ul class="pagination">
     {% if pagina != 1 %}
                  <li class="page-item"><a class="page-link" href="/admin/listausuario/{{pagina - 1}}">&laquo;</a></li>
    {% if pagina != 2 %}
                  <li class="page-item"><a class="page-link" href="/admin/listausuario/{{pagina - 2}}">{{pagina - 2}}</a></li>
    {% endif %}
                  <li class="page-item"><a class="page-link" href="/admin/listausuario/{{pagina - 1}}">{{pagina - 1}}</a></li>
     {% endif %}
                  
                  <li class="page-item active"><a class="page-link" href="/admin/listausuario/{{pagina}}">{{pagina}}</a></li>
                  
    {% if pagina != totalpgs %} 
                  <li class="page-item"><a class="page-link" href="/admin/listausuario/{{pagina + 1}}">{{pagina + 1}}</a></li>
    {% if pagina != (totalpgs - 1 )%}
                  <li class="page-item"><a class="page-link" href="/admin/listausuario/{{pagina + 2}}">{{pagina + 2}}</a></li>
    {% endif %}              
                  <li class="page-item"><a class="page-link" href="/admin/listausuario/{{pagina + 1}}">&raquo;</a></li>
    {% endif %}
    </ul>  
{% endif %}

{% if ( pagina * 5 ) >= totalreg %}
    <p>(De {{iniciolimit + 1}} a {{totalreg}}. Total, {{totalreg}} registros.)</p>
{% else %}
    <p>(De {{iniciolimit + 1}} a {{pagina * 5}}. Total, {{totalreg}} registros.)</p>
{% endif %}
</div>

</section>

{% block footer %}
       {# <footer class="footer">            
                <p>Copyright <script>document.write(new Date().getFullYear())</script> &copy; <a href="http://www.devcrud.com">Xokas and co</a></p>
            </footer>#}
            <div class="fondoseccion text-center footer-pd">
                AIRES
            </div>
{% endblock %}
{% endblock %}

templates/admvuelos.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
{{ parent() }}


<script>
    function confirmacion()
    {

        var respuesta=confirm("¿Desea realmente borrar el registro?");
        if (respuesta==true)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
</script>
{% endblock %}
{% block title %}Register{% endblock %}

{% block body %}
{{ parent() }}
<header>

</header>

<section class="pt-150 cuerpo fondoseccion">
<div class=" w-50 offset-lg-3 offset-md-1 offset-sm-3">
<h2 class="text-center">LISTADO DE VUELOS</h2>
</div>
<table class="table table-dark table-hover w-50  offset-lg-3 offset-md-1 offset-sm-1">
<thead>
<tr>
<th class="d-none">ID</th><th>AVION</th><th>RUTA</th><th>SALIDA</th><th>LLEGADA</th><th>PRECIO BASE</th><th>ESTADO</th><th>ACCIONES</th>
</tr>
</thead>
<tbody>
{% for vuelo in vuelos %}
<tr id="{{vuelo.id}}" class="filasjuego tr:hover">
<td class="d-none">{{vuelo.id}}</td><td>{{vuelo.avion}}</td><td>{{vuelo.ruta}}</td><td>{{vuelo.fecha_salida|date('Y-m-d H:i:s') }}</td><td>{{vuelo.fecha_llegada|date('Y-m-d H:i:s')}}</td><td>{{vuelo.precio_base}}</td><td>{{vuelo.estado}}</td><td><a href="/admin/editavuelo/{{vuelo.id}}" class=""><i class="fas fa-edit "></i></a><a href="/admin/deletevuelo/{{vuelo.id}}" onclick="return confirmacion()"><i class="fas fa-trash ml-5"></i></a></td>
</tr>
{% endfor %}
</tbody>
</table>

<div class="d-flex justify-content-between w-50  offset-lg-3 offset-md-1 offset-sm-3">

<a href="/admin/nuevovuelo" class="btn btn-primary">Añadir</a>

{% if totalpgs > 0 %}
     <ul class="pagination">
     {% if pagina != 1 %}
                  <li class="page-item"><a class="page-link" href="/admin/listavuelo/{{pagina - 1}}">&laquo;</a></li>
    {% if pagina != 2 %}
                  <li class="page-item"><a class="page-link" href="/admin/listavuelo/{{pagina - 2}}">{{pagina - 2}}</a></li>
    {% endif %}
                  <li class="page-item"><a class="page-link" href="/admin/listavuelo/{{pagina - 1}}">{{pagina - 1}}</a></li>
     {% endif %}
                  
                  <li class="page-item active"><a class="page-link" href="/admin/listavuelo/{{pagina}}">{{pagina}}</a></li>
                  
    {% if pagina != totalpgs %} 
                  <li class="page-item"><a class="page-link" href="/admin/listavuelo/{{pagina + 1}}">{{pagina + 1}}</a></li>
    {% if pagina != (totalpgs - 1 )%}
                  <li class="page-item"><a class="page-link" href="/admin/listavuelo/{{pagina + 2}}">{{pagina + 2}}</a></li>
    {% endif %}              
                  <li class="page-item"><a class="page-link" href="/admin/listavuelo/{{pagina + 1}}">&raquo;</a></li>
    {% endif %}
    </ul>  
{% endif %}

{% if ( pagina * 5 ) >= totalreg %}
    <p>(De {{iniciolimit + 1}} a {{totalreg}}. Total, {{totalreg}} registros.)</p>
{% else %}
    <p>(De {{iniciolimit + 1}} a {{pagina * 5}}. Total, {{totalreg}} registros.)</p>
{% endif %}
</div>

</section>

{% block footer %}
       {# <footer class="footer">            
                <p>Copyright <script>document.write(new Date().getFullYear())</script> &copy; <a href="http://www.devcrud.com">Xokas and co</a></p>
            </footer>#}
            <div class="fondoseccion text-center footer-pd">
                AIRES
            </div>
{% endblock %}
{% endblock %}

templates/confirmaciontarjeta.html.twig
{% extends 'base.html.twig' %}

{% block title %}Checkin Success!{% endblock %}

{% block body %}

    {{ parent() }}
   {% for flash_error in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
    {% endfor %}
<header>

</header>
<section class="pt-150 cuerpo fondoseccion">
<div class="col-lg-8 offset-lg-2">
    <h1>!Check-in realizado¡</h1>
    
       <h2>Se ha enviado a su correo una copia de la tarjeta de embarque.</h2>
       <h2>Tambien puede descargarla pinchando <a href="">aqui</a>.</h2>
       <h2>Si tiene cualquier problema, no dude en contactarnos: <a href="mailto:infoaires@contacto.com">infoaires@contacto.com</a>.</h2>        
       <h3><a href="/misreservas/1">Volver</a></h3>
</div>
</section>

{% endblock %}

templates/facturacion.html.twig
{% extends 'base.html.twig' %}
 {% block stylesheets %}
        {{ parent() }}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        {% endblock %}

        {% block javascripts %}
         {{ parent() }}
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        {% endblock %}
{% block body %} 

<H2>DETALLES DE FACTURACION</h1>

<article class="cuadroresumen pt-100  d-flex">
    <article class="cuadroresumen col-lg-4 offset-lg-2">
        <h6>Vuelo Ida</h6>
        <h6>{{factura1.reserva.vuelo.ruta}}</h6>
        <h6>Fecha de Salida: {{factura1.reserva.vuelo.fecha_salida|date('Y-m-d H:i')}}</h6>
        <h6>Fecha de Llegada: {{factura1.reserva.vuelo.fecha_llegada|date('Y-m-d H:i')}}</h6>
        <h6>Avion: {{factura1.reserva.vuelo.avion.codigo}}</h6>
        <h6>Asiento: {{factura1.reserva.asiento.columna}}{{factura1.reserva.asiento.fila}}</h6>
        <h6>Clase: {{factura1.reserva.asiento.clase}}</h6>
        <h6>Precio Base: {{factura1.reserva.vuelo.precio_base}}€</h6>
        <h6>Tarifa: {{factura1.tarifables.nombre}}</h6>
        <h6>Descripcion: {{factura1.tarifables.descripcion}}</h6>
        <h6>Precio Añadido: {{factura1.tarifables.precio}}€</h6>
        {% if factura2 is defined %}
        <h6>Vuelo Vuelta</h6>
        <h6>{{factura2.reserva.vuelo.ruta}}</h6>
        <h6>Fecha de Salida: {{factura2.reserva.vuelo.fecha_salida|date('Y-m-d H:i')}}</h6>
        <h6>Fecha de Llegada: {{factura2.reserva.vuelo.fecha_llegada|date('Y-m-d H:i')}}</h6>
        <h6>Avion: {{factura2.reserva.vuelo.avion.codigo}}</h6>
        <h6>Asiento: {{factura2.reserva.asiento.columna}}{{factura2.reserva.asiento.fila}}</h6>
        <h6>Clase: {{factura2.reserva.asiento.clase}}</h6>
        <h6>Precio Base: {{factura2.reserva.vuelo.precio_base}}€</h6>
        <h6>Tarifa: {{factura2.tarifables.nombre}}</h6>
        <h6>Descripcion: {{factura2.tarifables.descripcion}}</h6>
        <h6>Precio Añadido: {{factura2.tarifables.precio}}€</h6>
        {% endif %}
    </article>
</article>

<h2 class="pt-50 text-center colorblack">PRECIO TOTAL: {{preciototal}}€</h2>



{% endblock %}
{% block footer %}

{% endblock %}

templates/nuevaruta.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{titulo}} Ruta{% endblock %}

{% block body %}
{{ parent() }}
    {% for flash_error in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
    {% endfor %}
<header>

</header>

<section class="pt-150 cuerpo fondoseccion">

<div class="col-lg-3 col-md-6 col-8 offset-lg-4 offset-md-3 offset-sm-2 border borderradius bg-secondary">
<h1 class="text-center text-primary">{{titulo}} Ruta</h1>
    {{ form_start(nuevarutaForm) }}
        {{ form_row(nuevarutaForm.origen) }}
        {{ form_row(nuevarutaForm.destino) }}
        <button type="submit" class="btn btn-primary mb-3">{{titulo}}</button>
        <a href="/admin/listaruta/1" class="float-right">Volver</a>
    {{ form_end(nuevarutaForm) }}

</div>

</section>
{% block footer %}
       {# <footer class="footer">            
                <p>Copyright <script>document.write(new Date().getFullYear())</script> &copy; <a href="http://www.devcrud.com">Xokas and co</a></p>
            </footer>#}
            <div class="fondoseccion text-center footer-pd">
                AIRES
            </div>
{% endblock %}
{% endblock %}

templates/nuevoaeropuerto.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{titulo}} Aeropuerto{% endblock %}

{% block body %}
{{ parent() }}
    {% for flash_error in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
    {% endfor %}
<header>

</header>

<section class="pt-150 cuerpo fondoseccion">

<div class="col-lg-3 col-md-6 col-8 offset-lg-4 offset-md-3 offset-sm-2 border borderradius bg-secondary">
<h1 class="text-center text-primary">{{titulo}} Aeropuerto</h1>
    {{ form_start(nuevoaeropuertoForm) }}
        {{ form_row(nuevoaeropuertoForm.nombre) }}
        {{ form_row(nuevoaeropuertoForm.localidad) }}
        <button type="submit" class="btn btn-primary mb-3">{{titulo}}</button>
        <a href="/admin/listaaeropuerto/1" class="float-right">Volver</a>
    {{ form_end(nuevoaeropuertoForm) }}

</div>

</section>
{% block footer %}
       {# <footer class="footer">            
                <p>Copyright <script>document.write(new Date().getFullYear())</script> &copy; <a href="http://www.devcrud.com">Xokas and co</a></p>
            </footer>#}
            <div class="fondoseccion text-center footer-pd">
                AIRES
            </div>
{% endblock %}
{% endblock %}

templates/nuevoavion.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <style>
        
        #contavion{
            position: absolute;
            left: 500px;
            top: 90px;
            border: 1px solid;
            width: 350px;
            height: 800px; 
        }
        #formuavion{
          position: absolute;
            left: 900px;
            top: 90px;
        }

         #leyenda{
         width: 150px;
         height: 150px;
         position: absolute;
         left: 0px;
         top: 300px;
         border: 1px solid black;
         display: flex;
         flex-direction:column;
         justify-content:space-between;
        }

         #marcobusiness{
         width: 40px;
         height: 40px;
         background-Color: #fad02d;
         }

         #marcoprioritario{
         width: 40px;
         height: 40px;
         background-Color: #bc7a5c;
         }

         #marcoregular{
         width: 40px;
         height: 40px;
         background-Color: #3f4e9b;  
         }
    </style>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('assets/vendors/jquery/avion.js') }}" type="text/javascript"></script>
{% endblock %}
{% block body %}
{{ parent() }}
   <section>
   <div id="contavion">
   </div>
   <article id="formuavion">
   
   <fieldset>
    <legend>Seleccione modelo: </legend>
    <label for="airbus" id="airbuslbl">Airbus</label>
    <input type="radio" name="radio-1" id="airbus" checked>
    <label for="boeing" id="boeinglbl">Boeing</label>
    <input type="radio" name="radio-1" id="boeing">
  </fieldset>



   <div id="leyenda">
   <div class="d-flex ">
   <label for="codigoavion">Business:</label>
   <div id="marcobusiness"></div>
   </div>
   <div class="d-flex">
   <label for="codigoavion">Prioritario:</label>
   <div id="marcoprioritario"></div>
   </div>
   <div class="d-flex">
   <label for="codigoavion">Regular:</label>
   <div id="marcoregular"></div>
   </div>
   </div>
  </article>
   </section>
{% endblock %}

templates/nuevoavion2.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{titulo}} Avión{% endblock %}

{% block body %}
{{ parent() }}
    {% for flash_error in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
    {% endfor %}
<header>

</header>

<section class="pt-150 cuerpo fondoseccion">

<div class="col-lg-3 col-md-6 col-8 offset-lg-4 offset-md-3 offset-sm-2 border borderradius bg-secondary">
<h1 class="text-center text-primary">{{titulo}} Avión</h1>
    {{ form_start(nuevoavionForm) }}
        {{ form_row(nuevoavionForm.codigo) }}
        {{ form_row(nuevoavionForm.modelo) }}
        <button type="submit" class="btn btn-primary mb-3">{{titulo}}</button>
        <a href="/admin/listaavion/1" class="float-right">Volver</a>
    {{ form_end(nuevoavionForm) }}

</div>

</section>
{% block footer %}
       {# <footer class="footer">            
                <p>Copyright <script>document.write(new Date().getFullYear())</script> &copy; <a href="http://www.devcrud.com">Xokas and co</a></p>
            </footer>#}
            <div class="fondoseccion text-center footer-pd">
                AIRES
            </div>
{% endblock %}
{% endblock %}

templates/resumenpedido.html.twig
{% extends 'base.html.twig' %}

{% block title %}Resumen Reserva{% endblock %}

{% block body %}
{{ parent() }}
    {% for flash_error in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
    {% endfor %}
<header>

</header>

<section class="pt-100 cuerpo  d-flex flex-column fondoseccion">
<h2 class="text-center colorblack">RESUMEN DE LA RESERVA</h2>
<article class="cuadroresumen pt-100  d-flex">
    <article class="cuadroresumen col-lg-4 offset-lg-2">
        <h3>Vuelo Ida</h3>
        <h3>{{vueloida.ruta}}</h3>
        <h3>Fecha de Salida: {{vueloida.fecha_salida|date('Y-m-d H:i')}}</h3>
        <h3>Fecha de Llegada: {{vueloida.fecha_llegada|date('Y-m-d H:i')}}</h3>
        <h3>Avion: {{vueloida.avion.codigo}}</h3>
        <h3>Asiento: {{asientoelegidoIda.columna}}{{asientoelegidoIda.fila}}</h3>
        <h3>Clase: {{asientoelegidoIda.clase}}</h3>
        <h3>Precio Base: {{vueloida.precio_base}}€</h3>
        </br>
        <h3>Tarifa: {{tarifa.nombre}}</h3>
        <h3>Descripcion: {{tarifa.descripcion}}</h3>
        <h3>Precio Añadido: {{tarifa.precio}}€</h3>
    </article>
     {% if vuelovuelta is defined %}
    <article class="cuadroresumen col-lg-4 offset-lg-1">
        <h3>Vuelo Vuelta</h3>
        <h3>{{vuelovuelta.ruta}}</h3>
        <h3>Fecha de Salida: {{vuelovuelta.fecha_salida|date('Y-m-d H:i')}}</h3>
        <h3>Fecha de Llegada: {{vuelovuelta.fecha_llegada|date('Y-m-d H:i')}}</h3>
        <h3>Avion: {{vuelovuelta.avion.codigo}}</h3>
        <h3>Asiento: {{asientoelegidoVuelta.columna}}{{asientoelegidoVuelta.fila}}</h3>
        <h3>Clase: {{asientoelegidoVuelta.clase}}</h3>
        <h3>Precio Base: {{vuelovuelta.precio_base}}€</h3>
        </br>
        <h3>Tarifa: {{tarifa.nombre}}</h3>
        <h3>Descripcion: {{tarifa.descripcion}}</h3>
        <h3>Precio Añadido: {{tarifa.precio}}€</h3>
    </article>
    {% endif %}
</article>
<h2 class="pt-50 text-center colorblack">PRECIO TOTAL: {{preciototal}}€</h2>

<div class="mb-50 m-auto ">
    <form action="/checkout" method="POST">
        <input type="hidden" name="preciototal" value="{{preciototal}}"></input>
        <input type="hidden" name="vueloidaid" value="{{vueloida.id}}"></input>
         <input type="hidden" name="asientoidaid" value="{{asientoelegidoIda.id}}"></input>
          {% if vuelovuelta is defined %}
        <input type="hidden" name="vuelovueltaid" value="{{vuelovuelta.id}}"></input>
        <input type="hidden" name="asientovueltaid" value="{{asientoelegidoVuelta.id}}"></input>
          {% endif %}
        <input type="hidden" name="tarifaid" value="{{tarifa.id}}"></input>
        <button type="submit" class="btn btn-primary colorwhite">REALIZAR PAGO</button>
    </form>
<div>
</section>
{% block footer %}
       {# <footer class="footer">            
                <p>Copyright <script>document.write(new Date().getFullYear())</script> &copy; <a href="http://www.devcrud.com">Xokas and co</a></p>
            </footer>#}
            <div class="fondoseccion text-center footer-pd">
                AIRES
            </div>
{% endblock %}
{% endblock %}